name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          .deps/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v4

    - run: ls -la ~/.cargo/bin/
    - run: ls -la target/
    # - run: rustup update
    # - run: cargo --version
    # - run: cargo x install-dev-tools
    # - run: cargo x check
